name: Test
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: keyboard_handler
        target-ros2-distro: rolling
    - uses: actions/upload-artifact@v2
      with:
        name: colcon-logs
        path: ros_ws/log
